### ISSUE TITLE
AFFiNE PRO V2 Design

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE-Design#10]
```[tasklist]
### Tasks
- [x] new Title section
- [x] trusted by section
- [x] Why should I use section
- [x] Write / Draw / Plan
- [x] AFFiNE builds everything in public
- [x] User Stories
- [x] Build with Blocksuite and OctoBase
```

**Comment by xell** [comment]
Should this issue be transfered to the private repo of https://github.com/toeverything/affine.pro-next ?
